apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.pvcName }}
  labels:
    {{- include "amlfs-shared-storage.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.storage.accessModes }}
    - {{ . }}
    {{- end }}
  storageClassName: {{ include "amlfs-shared-storage.fullname" . }}-azurelustre
  resources:
    requests:
      storage: {{ .Values.storage.size }}
