apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-labeler-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-labeler-role
rules:
- apiGroups: [""] # Core API group
  resources: ["nodes"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-labeler-rolebinding
subjects:
- kind: ServiceAccount
  name: node-labeler-sa
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: node-labeler-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: node-labeler
spec:
  selector:
    matchLabels:
      app: node-labeler
  template:
    metadata:
      labels:
        app: node-labeler
    spec:
      serviceAccountName: node-labeler-sa
      containers:
      - name: labeler
        image: mcr.microsoft.com/cbl-mariner/busybox:1.35
        command: ["sh", "-c", "echo 'Task completed'; sleep 3600"]
      initContainers:
      - name: torset-discovery
        image: mcr.microsoft.com/aznhc/aznhc-nv:1.2.0
        securityContext:
          capabilities:
            add:
            - SYS_RESOURCE
        volumeMounts:
        - name: workdir
          mountPath: /work
        command: ["/bin/bash", "-lc"]
        args:
        - |
          ulimit -l unlimited
          set -euo pipefail

          # Skip if no RDMA devices present
          if [ ! -d /dev/infiniband ]; then
            echo "No RDMA devices found; skipping torset discovery."
            exit 0
          fi

          # Collect all HCAs' GUIDs
          guids=$(ibv_devinfo | grep hca | awk '{print $2}' \
              | xargs -I% ibstat "%" \
              | grep "Port GUID" | awk -F: '{print $2}' | sed 's/^0x00/0x/')

          guid_file=/work/guids.txt
          echo "$guids" > "$guid_file"

          topo_file=/work/topology.txt
          SHARP_SMX_UCX_INTERFACE=mlx5_0:1 \
              /opt/mellanox/sharp/bin/sharp_cmd topology \
              --ib-dev mlx5_0:1 \
              --guids_file "$guid_file" \
              --topology_file "$topo_file" || true

          # Parse torset from topology
          if [ -f "$topo_file" ]; then
            leafs=$(grep "Nodes=" "$topo_file" | awk '{print $1}' | cut -d= -f2)

            declare -A parent_counts
            while read -r line; do
              sw_name=$(echo "$line" | awk '{print $1}' | cut -d= -f2)
              switches_field=$(echo "$line" | grep "Switches=" | awk '{print $2}' | cut -d= -f2)
              IFS=',' read -ra switches <<< "$switches_field"
              for leaf in $leafs; do
                for s in "${switches[@]}"; do
                  if [[ "$s" == "$leaf" ]]; then
                    parent_counts["$sw_name"]=1
                  fi
                done
              done
            done < <(grep "Switches=" "$topo_file")

            declare -A torset_candidates
            for parent in "${!parent_counts[@]}"; do
              while read -r line; do
                sw_name=$(echo "$line" | awk '{print $1}' | cut -d= -f2)
                switches_field=$(echo "$line" | grep "Switches=" | awk '{print $2}' | cut -d= -f2 || echo "")
                IFS=',' read -ra switches <<< "$switches_field"
                for p in "${switches[@]}"; do
                  if [[ "$p" == "$parent" ]]; then
                    torset_candidates["$sw_name"]=1
                  fi
                done
              done < <(grep "Switches=" "$topo_file")
            done

            torset=$(printf "%s\n" "${!torset_candidates[@]}" | head -n1)
            echo -n "$torset" > /work/torset
          fi
      - name: init-labeler
        image: mcr.microsoft.com/oss/kubernetes/kubectl:v1.26.3
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: host-data
          mountPath: /var/lib/hyperv/.kvp_pool_3
        - name: workdir
          mountPath: /work
        command: ["/bin/sh", "-c"] 
        args:
          - |
            for kv in $(cat /var/lib/hyperv/.kvp_pool_3 | sed 's/\x0/ /g;s/  */ /g' | sed -E 's/([^ ]+) ([^ ]+)/\1=\2\n/g; s/ ([^ ]+)$/=\1/'); do
              echo $kv
              kubectl label node "$NODE_NAME" "hyperv/$kv" --overwrite
            done

            pkey=$(cat /sys/class/infiniband/mlx5_*/ports/1/pkeys/* 2>/dev/null | grep 0x8 | sort -u)
            if [ -n "$pkey" ]; then
              kubectl label node "$NODE_NAME" "ib/pkey=$pkey" --overwrite
            fi

            if [ -s /work/torset ]; then
              torset=$(cat /work/torset)
              kubectl label node "$NODE_NAME" "ib/torset=$torset" --overwrite
            fi
      volumes:
      - name: host-data
        hostPath:
          path: /var/lib/hyperv/.kvp_pool_3
      - name: workdir
        emptyDir: {}