# Default values for dataset-download
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Dataset configuration
dataset:
  name: "allenai/c4"
  subset: "en"
  splits: ["train", "val"]
  concatTokens: 2048
  tokenizer: "EleutherAI/gpt-neox-20b"
  eosText: "<|endoftext|>"
  outputPath: "my-copy-c4"

# Container image configuration
image:
  repository: ghcr.io/azure/ai-infrastructure-on-azure/llm-foundry
  tag: latest
  pullPolicy: IfNotPresent

# Storage configuration
storage:
  # Mount path where the shared storage will be mounted
  mount: "/data"
  # Name of the existing PVC to use for shared storage
  # This should be created by the shared-storage helm chart
  pvcName: "shared-blob-storage"

# Resource configuration
resources:
  # Number of worker processes for dataset conversion
  workers: 8
  # CPU per worker (will be multiplied by workers in template)
  cpuPerWorker: 2
  memoryPerWorkerGi: 4
  # shared memory size for the job
  shmSize: "8Gi"

# Job configuration
job:
  # Restart policy for the job
  restartPolicy: Never
  # Backoff limit for failed pods
  backoffLimit: 3
  # Time to live after job completion (in seconds)
  ttlSecondsAfterFinished: 3600

# Node selector for job placement
nodeSelector: {}

# Tolerations for node taints
tolerations: []

# Affinity rules
affinity: {}
