apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "blob-shared-storage.fullname" . }}-blob-storage
  labels:
    {{- include "blob-shared-storage.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
provisioner: blob.csi.azure.com
reclaimPolicy: {{ .Values.storage.reclaimPolicy }}
volumeBindingMode: {{ .Values.storage.volumeBindingMode }}
allowVolumeExpansion: true
mountOptions:
  {{- range .Values.storage.mountOptions }}
  - {{ . | quote }}
  {{- end }}
parameters:
  skuName: {{ .Values.storage.skuName }}
