apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prepare-data.fullname" . }}-scripts
  labels:
    {{- include "prepare-data.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "scripts/*.py").AsConfig | indent 2 }}
