apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "prepare-data.fullname" . }}-extract
  labels:
    {{- include "prepare-data.labels" . | nindent 4 }}
    app.kubernetes.io/component: extract
spec:
  parallelism: {{ .Values.pipeline.parallelism }}
  completions: {{ .Values.pipeline.completions }}
  completionMode: Indexed
  template:
    spec:
      restartPolicy: Never
      initContainers:
      - name: wait-for-download
        image: {{ .Values.image.nemo }}
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "Waiting for download to complete..."
          while [ $(find {{ .Values.pipeline.dataDirectory }} -name ".download-*-complete" | wc -l) -lt {{ .Values.pipeline.completions }} ]; do
            echo "Found $(find {{ .Values.pipeline.dataDirectory }} -name ".download-*-complete" | wc -l) of {{ .Values.pipeline.completions }} workers completed"
            sleep 10
          done
          echo "All download workers completed, starting extract..."
        volumeMounts:
        - name: shared-storage
          mountPath: {{ .Values.pipeline.dataDirectory }}
      containers:
      - name: extract
        image: {{ .Values.image.nemo }}
        command: ["python", "/scripts/extract.py"]
        args:
        - "--directory={{ .Values.pipeline.dataDirectory }}"
        - "--worker-index=$(JOB_COMPLETION_INDEX)"
        - "--total-workers={{ .Values.pipeline.completions }}"
        env:
        - name: JOB_COMPLETION_INDEX
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['batch.kubernetes.io/job-completion-index']
        volumeMounts:
        - name: shared-storage
          mountPath: {{ .Values.pipeline.dataDirectory }}
        - name: scripts
          mountPath: /scripts
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        lifecycle:
          postStart:
            exec:
              command: ["pip", "install", "zstandard"]
      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.name }}
      - name: scripts
        configMap:
          name: {{ include "prepare-data.fullname" . }}-scripts
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
