apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "prepare-data.fullname" . }}-download
  labels:
    {{- include "prepare-data.labels" . | nindent 4 }}
    app.kubernetes.io/component: download
spec:
  parallelism: {{ .Values.pipeline.download.parallelism }}
  completions: {{ .Values.pipeline.download.parallelism }}
  completionMode: Indexed
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: download
        image: {{ .Values.pipeline.download.image }}
        command: ["python", "/scripts/download_slimpajama.py"]
        args:
        - "--directory=/shared-data/{{ .Values.pipeline.dataDirectory }}"
        - "--worker-index=$(JOB_COMPLETION_INDEX)"
        - "--total-workers={{ .Values.pipeline.download.parallelism }}"
        {{- if .Values.pipeline.fullDataset }}
        - "--full-dataset"
        {{- else }}
        - "--sample-files={{ .Values.pipeline.sampleFiles }}"
        {{- end }}
        env:
        - name: JOB_COMPLETION_INDEX
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['batch.kubernetes.io/job-completion-index']
        volumeMounts:
        - name: shared-storage
          mountPath: /shared-data
        - name: scripts
          mountPath: /scripts
        resources:
          {{- toYaml .Values.pipeline.download.resources | nindent 10 }}
        lifecycle:
          postStart:
            exec:
              command: ["pip", "install", "requests"]
      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.name }}
      - name: scripts
        configMap:
          name: {{ include "prepare-data.fullname" . }}-scripts
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
