apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "amlfs-shared-storage.fullname" . }}-azurelustre
  labels:
    {{- include "amlfs-shared-storage.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
parameters:
  sku-name: {{ .Values.storage.amlfs.skuName | quote }}
  zones: {{ .Values.storage.amlfs.zones | quote }}
  maintenance-day-of-week: {{ .Values.storage.amlfs.maintenanceDayOfWeek | quote }}
  maintenance-time-of-day-utc: {{ .Values.storage.amlfs.maintenanceTimeOfDayUtc | quote }}
provisioner: azurelustre.csi.azure.com
reclaimPolicy: {{ .Values.storage.reclaimPolicy }}
volumeBindingMode: {{ .Values.storage.volumeBindingMode }}
mountOptions:
  {{- range .Values.storage.mountOptions }}
  - {{ . | quote }}
  {{- end }}
