# Default values for shared-storage
# This is a YAML-formatted file.

# Storage configuration
storage:
  # PVC name that will be created
  pvcName: "shared-blob-storage"
  # Storage size for the shared volume
  size: "10Ti"
  # Azure storage account SKU
  skuName: "Standard_LRS"
  # Access modes for the PVC
  accessModes:
    - ReadWriteMany
  # Reclaim policy for dynamically created storage
  reclaimPolicy: "Delete"
  # Volume binding mode
  volumeBindingMode: "Immediate"
  
  # Blobfuse mount options
  mountOptions:
    - "-o allow_other"
    - "--use-attr-cache=true"
    - "--cancel-list-on-mount-seconds=10"
    - "-o attr_timeout=120"
    - "-o entry_timeout=120"
    - "-o negative_timeout=120"
    - "--log-level=LOG_WARNING"
    - "--file-cache-timeout-in-seconds=120"
    - "--block-cache"
    - "--block-cache-block-size=32"

# Global annotations that will be applied to all resources
annotations: {}

# Global labels that will be applied to all resources  
labels: {}
