apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.pod.name }}
  labels:
    {{- include "fio.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  containers:
  - name: {{ .Values.pod.containerName }}
    image: {{ .Values.pod.image }}
    command: ["/bin/sh"]
    args:
      - -c
      - |
        apk add --no-cache fio && \
        echo "Running fio test..." && \
        {{- if .Values.fio.timeBased }}
        fio --name={{ .Values.fio.testName }} --filename={{ .Values.fio.filename }} --size={{ .Values.fio.size }} --bs={{ .Values.fio.blockSize }} --rw={{ .Values.fio.readWrite }} --ioengine={{ .Values.fio.ioEngine }} --direct={{ .Values.fio.direct }} --numjobs={{ .Values.fio.numJobs }} --runtime={{ .Values.fio.runtime }} --time_based {{ .Values.fio.additionalOptions }} && \
        {{- else }}
        fio --name={{ .Values.fio.testName }} --filename={{ .Values.fio.filename }} --size={{ .Values.fio.size }} --bs={{ .Values.fio.blockSize }} --rw={{ .Values.fio.readWrite }} --ioengine={{ .Values.fio.ioEngine }} --direct={{ .Values.fio.direct }} --numjobs={{ .Values.fio.numJobs }} {{ .Values.fio.additionalOptions }} && \
        {{- end }}
        echo "fio test completed. Sleeping for debugging ({{ .Values.sleepDuration }}s)..." && sleep {{ .Values.sleepDuration }}
    volumeMounts:
    - name: blob-storage
      mountPath: {{ .Values.pod.mountPath }}
    {{- if .Values.resources }}
    resources:
      {{- toYaml .Values.resources | nindent 6 }}
    {{- end }}
  volumes:
  - name: blob-storage
    persistentVolumeClaim:
      claimName: {{ .Release.Name }}-pvc
  restartPolicy: {{ .Values.pod.restartPolicy }}
