apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storage.className }}
  labels:
    {{- include "fio.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
mountOptions:
  {{- range .Values.storage.mountOptions }}
  - {{ . | quote }}
  {{- end }}
parameters:
  skuName: {{ .Values.storage.skuName }}
provisioner: blob.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
