name: Build & Push Megatron-LM Container Image

on:
  push:
    branches:
      - main
      - feature/megatronlm-aks
    paths:
      - examples/megatron-lm/GPT3-175B/docker/Dockerfile
      - .github/workflows/build_megatron_image.yaml

  workflow_dispatch:

jobs:
  build_push:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    permissions:
      contents: read
      packages: write

    steps:
    - name: Maximize build space
      uses: AdityaGarg8/remove-unwanted-software@v5
      with:
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor}}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate tags
      id: tag
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/azure/ai-infrastructure-on-azure/megatron-lm
        tags: |
          type=raw,value=latest
          type=schedule,pattern={{date 'YYYYMMDD-hhmmss' tz='Europe/London'}}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: examples/megatron-lm/GPT3-175B/docker
        file: examples/megatron-lm/GPT3-175B/docker/Dockerfile
        push: true
        tags: ${{ steps.tag.outputs.tags }}
        labels: ${{ steps.tag.outputs.labels }}
